# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\info1\PycharmProjects\interfaceListeView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.btnQuitter = QtWidgets.QPushButton(Dialog)
        self.btnQuitter.setGeometry(QtCore.QRect(130, 240, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnQuitter.setFont(font)
        self.btnQuitter.setObjectName("btnQuitter")
        self.listesViewEtudiants = QtWidgets.QListView(Dialog)
        self.listesViewEtudiants.setGeometry(QtCore.QRect(50, 20, 256, 192))
        self.listesViewEtudiants.setObjectName("listesViewEtudiants")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnQuitter.setText(_translate("Dialog", "Quitter"))
